In [2]:
import numpy as np 

In [3]:
#data types 
arr = np.array(["prime",{1,2,3},3.14])

print(arr, arr.dtype)

['prime' {1, 2, 3} 3.14] object


In [8]:
#Multidimensional arrays

arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print (arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [23]:
import numpy as np

# 3D array (2 x 3 x 2)
arr3D = np.array([[1,2], [3,4], [5,6],
                  [7,8], [9,10], [11,12]]).reshape(2,3,2)

print(arr3D)
print(arr3D.shape)

# Indexing
print(arr3D[1, 1, 0])

# Slicing
arr3D[:, 0, :] = 99

print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
9
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]
